/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import controller.datascontroller;
import javax.swing.JComboBox;

/**
 *
 * @author LENOVO
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    datascontroller dc;

    public home() {
        initComponents();
        dc = new datascontroller(this);

        dc.isitabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNama = new javax.swing.JTextField();
        btnTgl = new javax.swing.JTextField();
        btnNomor = new javax.swing.JTextField();
        btnTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnPlatKendaraan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnStatus = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnJenisKendaraan = new javax.swing.JComboBox<>();
        btnJenisServis = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnID.setEditable(false);
        btnID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDActionPerformed(evt);
            }
        });
        getContentPane().add(btnID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 203, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama Pelanggan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 84, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nomor Telepon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jenis kendaraan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 100, -1));

        btnNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 203, -1));

        btnTgl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTglActionPerformed(evt);
            }
        });
        getContentPane().add(btnTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 203, -1));

        btnNomor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNomorActionPerformed(evt);
            }
        });
        getContentPane().add(btnNomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 203, -1));

        btnTotal.setEditable(false);
        btnTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 203, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Plat Kendaraan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 100, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Total Biaya");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 84, -1));

        btnPlatKendaraan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPlatKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlatKendaraanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlatKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 203, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Jenis Servis");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 84, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Status");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 110, -1));

        btnStatus.setEditable(false);
        btnStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });
        getContentPane().add(btnStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 170, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Servis", "Nama Pelanggan", "Tanggal", "Telepon", "Jenis Kendaraan", "Plat Kendaraan", "Jenis Servis", "Total Biaya", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 121, 680, 160));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Tambah");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 130, 50));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Ubah");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 130, 50));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Hapus");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 130, 50));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("Reset");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 130, 50));

        btnJenisKendaraan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnJenisKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobil", "Motor" }));
        btnJenisKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJenisKendaraanActionPerformed(evt);
            }
        });
        getContentPane().add(btnJenisKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 200, -1));

        btnJenisServis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnJenisServis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ganti Oli", "Tambal Ban", "Ganti Kampas Rem", "Ganti Spare Part", "Tune Up" }));
        btnJenisServis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJenisServisActionPerformed(evt);
            }
        });
        getContentPane().add(btnJenisServis, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 200, -1));

        jButton2.setBackground(new java.awt.Color(63, 125, 118));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Pembayaran");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 220, 51));

        jButton1.setBackground(new java.awt.Color(63, 125, 118));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Riwayat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 220, 51));

        jButton4.setBackground(new java.awt.Color(63, 125, 118));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 220, 51));

        jButton3.setBackground(new java.awt.Color(63, 125, 118));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Registrasi Servis");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 51));

        jPanel1.setBackground(new java.awt.Color(182, 196, 190));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setBackground(new java.awt.Color(182, 196, 190));
        id.setForeground(new java.awt.Color(182, 196, 190));
        id.setText("jTextField1");
        id.setBorder(null);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 49, 71, -1));

        jLabel8.setBackground(new java.awt.Color(183, 201, 200));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(43, 39, 39));
        jLabel8.setText("Dashboard");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 180, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, -20, 740, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/3.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 120));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("ADMIN");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIDActionPerformed

    private void btnNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNamaActionPerformed

    private void btnTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTglActionPerformed

    private void btnNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNomorActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatusActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dc.insert();
        dc.isitabel();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.getSelectedRow();
        btnID.setText(jTable1.getValueAt(baris, 0).toString());
        btnNama.setText(jTable1.getValueAt(baris, 1).toString());
        btnTgl.setText(jTable1.getValueAt(baris, 2).toString());
        btnNomor.setText(jTable1.getValueAt(baris, 3).toString());
        btnJenisKendaraan.setSelectedItem(jTable1.getValueAt(baris, 4).toString());
        btnPlatKendaraan.setText(jTable1.getValueAt(baris, 5).toString());
        btnJenisServis.setSelectedItem(jTable1.getValueAt(baris, 6).toString());
        btnTotal.setText(jTable1.getValueAt(baris, 7).toString());
        btnStatus.setText(jTable1.getValueAt(baris, 8).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dc.update();
        dc.isitabel();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dc.delete();
        dc.isitabel();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        dc.reset();
        dc.isitabel();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnJenisKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJenisKendaraanActionPerformed
        // TODO add your handling code here:
        hitungTotalBiaya();
        
    }//GEN-LAST:event_btnJenisKendaraanActionPerformed

    private void btnJenisServisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJenisServisActionPerformed
        // TODO add your handling code here:
        hitungTotalBiaya();
        
    }//GEN-LAST:event_btnJenisServisActionPerformed
    private void hitungTotalBiaya() {
    if (btnJenisKendaraan == null || btnJenisServis == null || btnTotal == null) {
        // Jika salah satu komponen bernilai null, keluar dari metode
        return;
    }

    String jenisKendaraan = (String) btnJenisKendaraan.getSelectedItem();
    String jenisServis = (String) btnJenisServis.getSelectedItem();
    double total = 0;

    if (jenisKendaraan == null || jenisServis == null) {
        // Jika jenis kendaraan atau jenis servis bernilai null, keluar dari metode
        return;
    }

    switch (jenisKendaraan) {
        case "Mobil":
            switch (jenisServis) {
                case "Ganti Oli":
                    total = 650000;
                    break;
                case "Tambal Ban":
                    total = 50000;
                    break;
                case "Ganti Kampas Rem":
                    total = 85000;
                    break;
                case "Ganti Spare Part":
                    total = 100000;
                    break;
                case "Tune Up":
                    total = 150000;
                    break;
                default:
                    // Jika jenis servis tidak dikenal, beri nilai default
                    total = 0;
                    break;
            }
            break;
        case "Motor":
            switch (jenisServis) {
                case "Ganti Oli":
                    total = 25000;
                    break;
                case "Tambal Ban":
                    total = 10000;
                    break;
                case "Ganti Kampas Rem":
                    total = 35000;
                    break;
                case "Ganti Spare Part":
                    total = 45000;
                    break;
                case "Tune Up":
                    total = 75000;
                    break;
                default:
                    // Jika jenis servis tidak dikenal, beri nilai default
                    total = 0;
                    break;
            }
            break;
        default:
            // Jika jenis kendaraan tidak dikenal, beri nilai default
            total = 0;
            break;
    }

    // Atur nilai total biaya ke JTextField
    btnTotal.setText(String.valueOf(total));
}




    private void btnPlatKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlatKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlatKendaraanActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new pembayaran().show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //        history h = new history();
        //        h.setVisible(true);
        //        h.setLocationRelativeTo(null);
        new history().show();
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btnID;
    private javax.swing.JComboBox<String> btnJenisKendaraan;
    private javax.swing.JComboBox<String> btnJenisServis;
    private javax.swing.JTextField btnNama;
    private javax.swing.JTextField btnNomor;
    private javax.swing.JTextField btnPlatKendaraan;
    private javax.swing.JTextField btnStatus;
    private javax.swing.JTextField btnTgl;
    private javax.swing.JTextField btnTotal;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public JTextField getBtnID() {
        return btnID;
    }

    public void setBtnID(JTextField btnID) {
        this.btnID = btnID;
    }

    public JComboBox<String> getBtnJenisKendaraan() {
        return btnJenisKendaraan;
    }

    public void setBtnJenisKendaraan(JComboBox<String> btnJenisKendaraan) {
        this.btnJenisKendaraan = btnJenisKendaraan;
    }

    public JComboBox<String> getBtnJenisServis() {
        return btnJenisServis;
    }

    public void setBtnJenisServis(JComboBox<String> btnJenisServis) {
        this.btnJenisServis = btnJenisServis;
    }

    public JTextField getBtnNama() {
        return btnNama;
    }

    public void setBtnNama(JTextField btnNama) {
        this.btnNama = btnNama;
    }

    public JTextField getBtnNomor() {
        return btnNomor;
    }

    public void setBtnNomor(JTextField btnNomor) {
        this.btnNomor = btnNomor;
    }

    public JTextField getBtnPlatKendaraan() {
        return btnPlatKendaraan;
    }

    public void setBtnPlatKendaraan(JTextField btnPlatKendaraan) {
        this.btnPlatKendaraan = btnPlatKendaraan;
    }

    public JTextField getBtnStatus() {
        return btnStatus;
    }

    public void setBtnStatus(JTextField btnStatus) {
        this.btnStatus = btnStatus;
    }

    public JTextField getBtnTgl() {
        return btnTgl;
    }

    public void setBtnTgl(JTextField btnTgl) {
        this.btnTgl = btnTgl;
    }

    public JTextField getBtnTotal() {
        return btnTotal;
    }

    public void setBtnTotal(JTextField btnTotal) {
        this.btnTotal = btnTotal;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

}
