/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JTable;
import javax.swing.*;
import controller.controllerPembayaran;

/**
 *
 * @author HP
 */
public class pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form history
     */
   
    
    controllerPembayaran cp;
    public pembayaran() {
        initComponents();
      cp = new controllerPembayaran(this);
      cp.isiPembayaran();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPembayaran = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTxtKembalian = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTxtBayar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnRegis = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Servis", "Nama Pelanggan", "Tanggal", "No Telepon", "Jenis Kendaraan", "Plat kendaraan", "Jenis Service", "Total Biaya", "Status"
            }
        ));
        tabelPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPembayaran);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 670, 208));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Uang Bayar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, -1, -1));

        jTxtKembalian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKembalianActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total Biaya");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jTxtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 130, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Bayar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 140, 40));

        jTxtBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBayarActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Kembalian");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        jTxtID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("ID Servis");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 140, 40));

        btnRegis.setBackground(new java.awt.Color(63, 125, 118));
        btnRegis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegis.setForeground(new java.awt.Color(255, 255, 255));
        btnRegis.setText("Registrasi Servis");
        btnRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, 49));

        btnBayar.setBackground(new java.awt.Color(63, 125, 118));
        btnBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBayar.setForeground(new java.awt.Color(255, 255, 255));
        btnBayar.setText("Pembayaran");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 49));

        btnRiwayat.setBackground(new java.awt.Color(63, 125, 118));
        btnRiwayat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRiwayat.setForeground(new java.awt.Color(255, 255, 255));
        btnRiwayat.setText("Riwayat");
        btnRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatActionPerformed(evt);
            }
        });
        getContentPane().add(btnRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 220, 49));

        btnExit.setBackground(new java.awt.Color(63, 125, 118));
        btnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 220, 49));

        jPanel1.setBackground(new java.awt.Color(182, 196, 190));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setBackground(new java.awt.Color(182, 196, 190));
        id.setForeground(new java.awt.Color(182, 196, 190));
        id.setText("jTextField1");
        id.setBorder(null);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 49, 71, -1));

        jLabel8.setBackground(new java.awt.Color(183, 201, 200));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(43, 39, 39));
        jLabel8.setText("Menu Pembayaran");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 300, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, -20, 740, -1));

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 100, -1));

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setText("Search :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, 120));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("ADMIN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisActionPerformed
        new home().show();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void jTxtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKembalianActionPerformed

    private void jTxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTotalActionPerformed

    private void btnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatActionPerformed
        // TODO add your handling code here:
         new history().show();
        dispose();
    }//GEN-LAST:event_btnRiwayatActionPerformed

    private void jTxtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBayarActionPerformed

    private void jTxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIDActionPerformed

    private void tabelPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPembayaranMouseClicked
        // TODO add your handling code here:
        int baris = tabelPembayaran.getSelectedRow();
        jTxtID.setText(tabelPembayaran.getValueAt(baris, 0).toString());
        jTxtTotal.setText(tabelPembayaran.getValueAt(baris, 7).toString());
//        btnStatus.setText(jTable1.getValueAt(baris, 9).toString());
    }//GEN-LAST:event_tabelPembayaranMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Mengambil nilai dari text field

        // Menghitung kembalian

        // Mengecek apakah uang yang dibayar
        String ID = getjTxtID().getText();
        String Total = getjTxtTotal().getText();
        String Bayar = getjTxtBayar().getText();
        String Kembalian = getjTxtKembalian().getText();
        if (ID.isEmpty() || Total.isEmpty() || Bayar.isEmpty() ) {
            JOptionPane.showMessageDialog(this,"Harap isi semua field", "Peringatan",JOptionPane.WARNING_MESSAGE);
            return;
        }
        double total = Double.parseDouble(Total);
        double bayar = Double.parseDouble(Bayar);
        int id_servis = Integer.parseInt(ID);
        double kembalian = bayar - total;
        jTxtKembalian.setText(String.valueOf(kembalian));

        if (bayar >= total) {
            // Memanggil fungsi bayarLunas jika uang cukup
            JOptionPane.showMessageDialog(this, "SUDAH LUNAS!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
            cp.bayarLunas(id_servis);
        } else {
            // Menampilkan pesan jika uang tidak cukup
            JOptionPane.showMessageDialog(this, "Uang tidak cukup", "Error", JOptionPane.ERROR_MESSAGE);
        }
        cp.isiPembayaran();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        cp.Reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        cp.search();
    }//GEN-LAST:event_btnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRegis;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JButton btnsearch;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtBayar;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JTextField jTxtKembalian;
    private javax.swing.JTextField jTxtTotal;
    private javax.swing.JTable tabelPembayaran;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

    public JTable getTabelPembayaran() {
        return tabelPembayaran;
    }

    public void setTabelPembayaran(JTable tabelPembayaran) {
        this.tabelPembayaran = tabelPembayaran;
    }

    public JTextField getjTxtID() {
        return jTxtID;
    }

    public void setjTxtID(JTextField jTxtID) {
        this.jTxtID = jTxtID;
    }

    public JTextField getjTxtTotal() {
        return jTxtTotal;
    }

    public void setjTxtTotal(JTextField jTxtTotal) {
        this.jTxtTotal = jTxtTotal;
    }

    public JTextField getjTxtBayar() {
        return jTxtBayar;
    }

    public void setjTxtBayar(JTextField jTxtBayar) {
        this.jTxtBayar = jTxtBayar;
    }

    public JTextField getjTxtKembalian() {
        return jTxtKembalian;
    }

    public void setjTxtKembalian(JTextField jTxtKembalian) {
        this.jTxtKembalian = jTxtKembalian;
    }

    public JButton getBtnsearch() {
        return btnsearch;
    }

    public void setBtnsearch(JButton btnsearch) {
        this.btnsearch = btnsearch;
    }

    public JTextField getTxtsearch() {
        return txtsearch;
    }

    public void setTxtsearch(JTextField txtsearch) {
        this.txtsearch = txtsearch;
    }
    
}
